source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'CARFIT' do
     pod 'AWSCore'
     pod 'AWSAPIGateway'
     pod 'AWSCognito'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSS3'
#    pod 'AWSLambda'
#    pod 'AWSAutoScaling'
#    pod 'AWSCloudWatch'
#    pod 'AWSDynamoDB'
#    pod 'AWSEC2'
#    pod 'AWSElasticLoadBalancing'
#    pod 'AWSKinesis'
#    pod 'AWSMachineLearning'
#    pod 'AWSMobileAnalytics'
#    pod 'AWSSES'
#    pod 'AWSSimpleDB'
#    pod 'AWSSNS'
#    pod 'AWSSQS'
#    pod 'Fabric'
#    pod 'Crashlytics'
end
