source 'https://bitbucket.org/carfit_platform/pods.car.fit.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'CARFIT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for CARFIT
  pod 'CarFitiOSSDK' #, :path => '~mcclen/Developer/sdk.ios.car.fit'
  target 'CARFITTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
