source 'https://bitbucket.org/carfit_platform/pods.car.fit.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.3'

target 'CARFIT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for CARFIT
  pod 'CarFitiOSSDK' , :path => '../../sdk.ios.car.fit'
  pod 'Lock', '~> 1.26'
  pod 'Lock/TouchID'
  pod 'Lock/SMS'
  pod 'Lock/Email'
  pod 'BuddyBuildSDK'
  pod 'Fabric'
  pod 'Crashlytics'
  target 'CARFITTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
