/**
 * Created by brian on 1/3/17.
 */
const en = {
  general: {
    continue: ' Continue ',
  },
  login: {
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    marketingTitle1a: 'CARFIT PULS',
    marketingTitle1b: 'THE VIBRATION SENSOR',
    marketingText1a: 'CARFIT monitors the vibrations of your car at the steering wheel, like a doctor monitors your pulse.',
    marketingTitle2a: 'Works on any car',
    marketingText2a: 'CARFIT PULS is easily installed on any steering wheel.',
    marketingText2b: 'The CARFIT PULS automatically turns on whenever you get into your car and turns off after each drive to save battery. The battery lasts up to 2 years.',
    marketingTitle3a: 'Service made simple',
    marketingText3a: 'One button press away to schedule and visit your autoshop.',
    marketingText3b: 'The CARFIT PULS notifies you when it is time to check up your car.'

  },
  verification: {
    verification: 'Verification',
    welcome: 'Welcome to CARFIT!',
    instructions: 'A verification code to activate your account has been sent to:',
    pleaseEnterCode: 'Please enter the code below.',
    code: 'Code',
    resend: 'Resend Code',
  },
  resetPassword: {
    instructions: 'A password reset verification code has been sent to:',
    instructions2: 'Please enter the code below:',
    instructions3: 'Please enter your new password below:',
    newPassword: 'New Password',
    retypePassword: 'Retype Password',
    incorrect: 'Password is incorrect',
  },
  welcome: {
    welcome: 'Welcome',
    connect: 'Connect',
    welcomeToCarfit: 'Welcome to CARFIT!',
    helloMiles: 'Hello, I am Miles.',
    welcomeParagraph1: 'From now on I will be the voice of your car. Feel free to chat with me later!',
    welcomeParagraph2: 'CARFIT monitors the vibrations of your car at the steering wheel, like a doctor monitors your pulse.',
    welcomeParagraph3: 'I will now introduce you to the CARFIT app.',
    welcomeParagraph4: 'We will go through a quick guide for the following steps:',
    step1: 'CONNECT ',
    step2: 'INSTALL ',
    step3: 'APP ',
    stepDescription1: ' your CARFIT PULS sensor',
    stepDescription2: ' overview',
  },
  instructions: {
    enableBattery: 'Enable battery power',
    pullTab: 'Pull the plastic tab out of the CARFIT PULS sensor.',
    activateBluetooth: 'Activate Bluetooth',
    turnOnBLE: 'Turn your phone\'s Bluetooth on.',
    resetConnection: 'Reset connection',
    pressAndHold: 'Press & hold the center of the CARFIT PULS sensor for 10s to reset the sensor. \nTap to turn it on.',
    blePairing: 'Enable battery power',
    ensurePairing: 'Ensure the CARFIT PULS sensor in pairing mode with the center LED flashing.',
    selectBLE: 'Select your CARFIT PULS sensor from the list to connect.',
  },
  carInstallation: {
    installation: 'Installation',
    // Page One
    inCarInstallation: 'In-car installation',
    header1: 'Go to your car',
    message1: 'CARFIT PULS in-car installation',
    header2: 'Activate adhesive',
    message2: 'remove protective tape',
    header3: 'Position CARFIT PULS sensor',
    message3: 'stick onto steering wheel',
    header4: 'Register car',
    message4: 'enter LICENSE PLATE or VIN',
    header5: 'Configure your car',
    message5: 'verify & add your car\'s details',
    // Page two
    detail2a: 'Remove the protective tape from the bottom of the CARFIT PULS sensor',
    // Page three
    detail3a: 'Place the CARFIT PULS sensor on the top of the steering wheel hub with the lights facing the driver',
    detail3b: 'Ensure that the sensor is flat when the steering wheel is horizontal.',
    // Page four
    registerCar: 'registerCar',
    enterLicensePlate: 'Enter license plate here',
    enterByVin: 'Enter by VIN',
    enterVin: 'Enter VIN here',
    enterByLicensePlate: 'Enter by license plate',
  },
  vinLocations: {
    vinLocations: 'VIN locations',
    message1: 'To properly register your car CARFIT PULS needs your car’s VIN or license plate.',
    possibleLocations: 'Possible locations for the VIN:',
    driverDoor: 'Drivers side door jam or post',
    driverWindow: 'Drivers side front windshield',
    carTitle: 'Car title or documentation',
  },
  overview: {
    overview: 'Overview',
    header1: 'CARFIT PULS sensor',
    message1: 'tracks your cars health',
    header2: 'CARFIT concierge',
    message2: 'request an autoservice call',
    header3: 'askMiles',
    message3: 'CARFIT Zendesk support',
    header4: 'Usage',
    message4: 'displays your recent drives',
    header5: 'Service',
    message5: 'displays alerts, schedule and history',
    header6: 'Car details',
    message6: 'view or edit your car’s details',
    header7: 'Settings',
    message7: 'my cars (car details), sensors, my account, demo & more',
  },
  home: {
    alert: 'ALERT',
    usage: 'USAGE',
    value: 'VALUE',
    serviceNeeded: 'Service needed:',
    lastTrip: 'Last trip:',
    trending: 'Trending:',
    comingSoon: 'COMING SOON:',
  },
  settings: {
    settings: 'Settings',
    myCars: 'MY CARS',
    sensors: 'SENSORS',
    myAccount: 'MY ACCOUNT',
    demo: 'DEMO',
    useWiFi: 'USE WIFI',
    terms: 'Terms of use',
    privacy: 'Privacy',
    copyright: '© CARFIT 2017',
  },
  myCars: {
    myCars: 'My cars',
    active: 'Active',
    changeMyCar: 'Change my car',
  },
  details: {
    displayInfo: 'DISPLAY INFO',
    name: 'Name',
    mileage: 'Mileage',
    image: 'Image',

    connectedSensors: 'CONNECTED SENSORS',
    carfit: 'CARFIT',
    phone: 'Phone',

    info: 'INFO',
    year: 'Year',
    make: 'Make',
    model: 'Model',
    mpgCity: 'MPG city',
    mpgHighway: 'MPG highway',
    license: 'License plate',
    vin: 'VIN',
    drivenWheels: 'Driven wheels',
    trimLevel: 'Trim level',
    doors: 'Number of doors',
  },
  account: {
    accountType: 'Account Type',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email address',
    password: 'Password',
    changePassword: 'Change Password',
  },
  legal: {
    privacy: 'Privacy Policy',
    terms: 'Terms of Use'
  }
};
export default en;