/**
 * Translated March 29, 2017.
 */
const fr = {
  general: {
    continue: 'Continuez',
  },
  login: {
    email: 'E-mail',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié',
    marketingTitle1a: 'Capteur CARFIT PULS',
    marketingTitle1b: 'Le capteur de vibrations',
    marketingText1a: 'CARFIT surveille les vibrations au niveau du volant de votre véhicule, comme un médecin surveille votre pouls.',
    marketingTitle2a: 'Fonctionne avec toutes les voitures.',
    marketingText2a: 'Le capteur CARFIT PULS s\'installe très facilement sur n\'importe quel volant de voiture.',
    marketingText2b: 'Le capteur se réveille automatiquement dès que vous entrez dans votre véhicule et se met en veille après chaque trajet pour économiser de l\'énergie. La batterie interne a deux ans d\'autonomie.',
    marketingTitle3a: 'L\'entretien de votre véhicule rendu plus simple',
    marketingText3a: 'L\'entretien de votre véhicule est à portée de main.',
    marketingText3b: 'Le capteur CARFIT PULS vous prévient lorsqu\'une opération est à réaliser.'
  },
  verification: { // is this still required with Auth0?
    verification: 'Vérification',
    welcome: 'Bienvenue chez CARFIT !',
    instructions: 'Un code de validation vient de vous être envoyé.',
    pleaseEnterCode: 'Veuillez entrer le code ci-dessous.',
    code: 'Code',
    resend: 'Renvoyer le code.',
  },
  resetPassword: { // is this still required with Auth0?
    instructions: 'Un code de vérification pour la réinitialisation de votre mot de passe a été envoyé.',
    instructions2: 'Veuillez entrer le code ci-dessous.',
    instructions3: 'Veuillez entrer votre nouveau mot de passe ci-dessous.',
    newPassword: 'Nouveau mot de passe',
    retypePassword: 'Confirmez votre mot de passe',
    incorrect: 'Mot de passe incorrect',
  },
  welcome: {
    welcome: 'Bienvenue',
    connect: 'Se connecter',
    welcomeToCarfit: 'Bienvenue chez CARFIT!',
    helloMiles: 'Bonjour, je suis Miles.',
    welcomeParagraph1: 'Je suis la voix de votre voiture, vous pouvez discuter avec moi.',
    welcomeParagraph2: 'CARFIT surveille les vibrations au niveau du volant de votre véhicule, comme un médecin surveille votre pouls.',
    welcomeParagraph3: 'Je vais vous présenter l\'application CARFIT et vous guider vers les prochaines étapes.',
//    welcomeParagraph4: 'Guide rapide:',
    step1: 'Se connecter ',
    step2: 'Installer ',
    step3: 'Application ',
    stepDescription1: ' votre capteur CARFIT PULS',
    stepDescription2: ' synthèse',
  },
  instructions: {
    enableBattery: 'Activez la batterie.',
    pullTab: 'Retirez la languette en plastique située en-dessous du capteur.',
    activateBluetooth: 'Activer le Bluetooth.',
    turnOnBLE: 'Activez le Bluetooth de votre téléphone.',
    resetConnection: 'Réinitialiser la connexion.',
    pressAndHold: 'Maintenez pressé le bouton situé sur le dessus du capteur  pendant 10 secondes pour le réinitialiser. Appuyez sur le bouton pour l\'allumer.',
    blePairing: 'Activez la batterie.',
    ensurePairing: 'S\'assurer que le capteur est en mode appairage, avec la LED centrale clignotante.',
    selectBLE: 'Sélectionnez le  capteur CARFIT PULS dans la liste.',
  },
  carInstallation: {
    installation: 'Installation',
    // Page One
    inCarInstallation: 'Installation dans la voiture.',
    header1: 'Allez dans votre voiture.',
    message1: 'Installation du capteur CARFIT PULS dans votre voiture',
    header2: 'Préparez l\'adhésif',
    message2: 'Retirez la protection de l\'adhésif',
    header3: 'Positionnez le capteur',
    message3: 'Collez le capteur sur le volant',
    header4: 'Enregistrez votre véhicule',
    message4: 'Entrez votre plaque d\'immatriculation ou votre VIN',
    header5: 'Configurez votre véhicule',
    message5: 'Vérifiez et ajoutez des précisions',
    // Page two
    detail2a: 'Retirez la protection de l\'adhésif situé sous le capteur',
    // Page three
    detail3a: 'Collez le capteur sur le dessus du moyeu du volant, avec les LED face au conducteur.',
    detail3b: 'Assurez-vous que le capteur est bien horizontal lorsque le volant est droit.',
    // Page four
    registerCar: 'Enregistrez votre véhicule',
    enterLicensePlate: 'Entrez votre numéro d\'immatriculation',
    enterRegion: 'Entrez votre pays',
    enterByVin: 'S\'enregistrer par le VIN',
    enterVin: 'Entrez votre VIN',
    enterByLicensePlate: 'S\'enregistrer par le numéro d\'immatriculation',
    success: 'Voiture identifiée!',
    failure: 'Pas ma voiture'
  },
  vinLocations: {
    vinLocations: 'Trouvez votre VIN',
    message1: 'Pour enregistrer correctement votre véhicule, CARFIT a besoin de son immatriculation ou de son VIN.',
    possibleLocations: 'Emplacements possibles du VIN:',
    driverDoor: 'Autour de la porte conducteur',
    driverWindow: 'En bas du pare-brise, à l\'extérieur',
    carTitle: 'Sur la carte grise, champ E, ou sur la vignette du contrôle technique',
  },
  overview: {
    overview: 'Overview',
    header1: 'Capteur CARFIT PULS',
    message1: 'Surveille l\'état de santé de votre véhicule',
    header2: 'concierge CARFIT',
    message2: 'appelez-moi',
    header3: 'askMiles',
    message3: 'Miles le Bot et assistance',
    header4: 'Conduite',
    message4: 'Vos derniers trajets',
    header5: 'Entretien',
    message5: 'Historique, alertes, entretiens à venir',
    header6: 'Votre véhicule',
    message6: 'Voir et modifier votre véhicule',
    header7: 'Paramètres',
    message7: 'Véhicules, capteurs, compte, mode démo…',
  },
  home: {
    alert: 'Alertes',
    usage: 'Conduite',
    value: 'Valeur',
    serviceNeeded: 'Opération nécessaire',
    lastTrip: 'Dernier trajet',
    trending: 'Tendance',
    comingSoon: 'A venir',
    mileage: 'Entrez le kilométrage de votre véhicule ici.'
  },
  settings: {
    settings: 'Paramètres',
    myCars: 'Mes véhicules',
    sensors: 'Capteurs',
    myAccount: 'Mon compte',
    drive: 'Conduite',
    useWiFi: 'Utiliser le wifi seulement',
    terms: 'Conditions générales d\'utilisation',
    privacy: 'Politique de confidentialité',
    copyright: '© CARFIT 2017',
  },
  myCars: {
    myCars: 'Mes véhicules',
    active: 'Ma véhicule active',
    changeMyCar: 'Changer mon véhicule',
  },
  details: {
    displayInfo: 'Information de véhicule',
    name: 'Nom',
    mileage: 'Kilométrage',
    image: 'Photo',

    connectedSensors: 'Capteurs connectés',
    carfit: 'CARFIT',
    phone: 'Téléphone',

    info: 'Informations',
    year: 'Année',
    make: 'Constructeur',
    model: 'Modèle',
    mpgCity: 'Consommation urbaine (L/100km)',
    mpgHighway: 'Consommation autoroute (L/100km)',
    license: 'Numéro d\'immatriculation',
    vin: 'VIN',
    drivenWheels: 'Roues motrices',
    trimLevel: 'Niveau de finition',
    doors: 'Nombre de portes',
  },
  account: {
    accountType: 'Type de compte',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Adresse e-mail',
    identifier: 'Identifiant',
    password: 'Mot de passe',
    changePassword: 'Changer le mot de passe',
  },
  legal: {
    privacy: 'Politique de confidentialité',
    terms: 'Conditions générales d\'utilisation'
  },
  register: {
    signin: 'Se connecter',
    first: 'Prénom',
    last: 'Nom de famille',
    email: 'name@example.com',
    phone: '+XX XX XX XX XX X'
  }
};
export default fr;
