const country_codes = {
  "Albania": "AL",
  "Andorra": "AD",
  "Austria": "AT",
  "Belarus": "BY",
  "Belgium": "BE",
  "Bosnia": "BA",
  "Bulgaria": "BG",
  "Croatia": "HR",
  "Cyprus": "CY",
  "Czech Republic": "CZ",
  "Denmark": "DK",
  "Estonia": "EE",
  "Faroe Islands": "FO",
  "Finland": "FI",
  "France": "FR",
  "Germany": "DE",
  "Gibraltar": "GI",
  "Greece": "GR",
  "Hungary": "HU",
  "Iceland": "IS",
  "Ireland": "IE",
  "Isle of Man": "IM",
  "Italy": "IT",
  "Kosovo": "RS",
  "Latvia": "LV",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Macedonia": "MK",
  "Malta": "MT",
  "Moldova": "MD",
  "Monaco": "MC",
  "Montenegro": "ME",
  "Netherlands": "NL",
  "Norway": "NO",
  "Poland": "PL",
  "Portugal": "PT",
  "Romania": "RO",
  "San Marino": "SM",
  "Serbia": "RS",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Spain": "ES",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Ukraine": "UA",
  "United Kingdom": "GB",
  "Vatican City": "VA",
  "Yugoslavia": "RS"
};

export default country_codes;
